export const CHANGED_EXCEL_SIZE = 'CHANGED_EXCEL_SIZE';

export const ADD_EXCEL_SHEET = 'ADD_EXCEL_SHEET';

export const REMOVE_EXCEL_SHEET = 'REMOVE_EXCEL_SHEET';

export const CHANGE_EXCEL_SHEET_NAME = 'CHANGE_EXCEL_SHEET_NAME';

export const CHANGE_EXCEL_SHEET_SELECTED = 'CHANGE_EXCEL_SHEET_SELECTED';

export const DOWNLOAD_EXCEL = 'DOWNLOAD_EXCEL';

export const HIT_TEST_OPERATE = 'HIT_TEST_OPERATE';

export const GET_SELECTED_GRID = 'GET_SELECTED_GRID';

export const ADD_DRAG_IMAGE = 'ADD_DRAG_IMAGE';

export const SORT_MEDIA_ELEMENTS = 'SORT_MEDIA_ELEMENTS';





