export const CHANGED_EXCEL_SIZE = 'CHANGED_EXCEL_SIZE';

export const ADD_EXCEL_SHEET = 'ADD_EXCEL_SHEET';

export const REMOVE_EXCEL_SHEET = 'REMOVE_EXCEL_SHEET';

export const CHANGE_EXCEL_SHEET_NAME = 'CHANGE_EXCEL_SHEET_NAME';

export const CHANGE_EXCEL_SHEET_SELECTED = 'CHANGE_EXCEL_SHEET_SELECTED';

export const DOWNLOAD_EXCEL = 'DOWNLOAD_EXCEL';